//! Build script: dynamically generate the `MIGRATIONS` const from SQL files.
//!
//! Scans `src/db/migrations/` for files named `V{n}__{name}.sql`, parses the
//! version and name from the filename, reads each SQL file to extract the
//! target table/view name, and emits `$OUT_DIR/migrations.rs` containing:
//!
//! ```ignore
//! pub const MIGRATIONS: &[Migration] = &[ /* ... */ ];
//! ```
//!
//! The generated code is `include!`-d into `src/db/mod.rs`.

use std::path::Path;

const MIGRATIONS_DIR: &str = "src/db/migrations";

fn main() {
    println!("cargo:rerun-if-changed={}", MIGRATIONS_DIR);

    let migrations = collect_migrations(MIGRATIONS_DIR);

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("migrations.rs");

    let mut content = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // Source of truth: files in src/db/migrations/.\n\n",
    );
    content.push_str("use crate::migrate::Migration;\n\n");
    content.push_str("pub const MIGRATIONS: &[Migration] = &[\n");

    for m in &migrations {
        let version = m.version;
        let name = &m.name;
        let table_name = &m.table_name;
        let is_view = m.is_view;
        let include_path = format!("{}/{}", MIGRATIONS_DIR, m.filename);
        content.push_str(&format!(
            "    Migration {{\n\
             \x20   version: {version},\n\
             \x20   name: \"{name}\",\n\
             \x20   table_name: \"{table_name}\",\n\
             \x20   sql: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{include_path}\")),\n\
             \x20   is_view: {is_view},\n\
             \x20   }},\n",
        ));
    }

    content.push_str("];\n");

    std::fs::write(&dest, &content).expect("failed to write migrations.rs");
}

struct MigrationEntry {
    version: i32,
    name: String,
    table_name: String,
    is_view: bool,
    filename: String,
}

fn collect_migrations(dir: &str) -> Vec<MigrationEntry> {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("failed to read {dir}: {e}"))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let filename = entry.file_name().to_str()?.to_string();
            let meta = entry.metadata().ok()?;
            if !meta.is_file() {
                return None;
            }
            parse_migration_filename(&filename).map(|(version, name)| MigrationEntry {
                version,
                name,
                table_name: String::new(),
                is_view: false,
                filename,
            })
        })
        .collect();

    entries.sort_by_key(|m| m.version);

    for entry in &mut entries {
        let path = format!("{}/{}", dir, entry.filename);
        let sql =
            std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {path}: {e}"));
        (entry.table_name, entry.is_view) = extract_table_and_view(&sql).unwrap_or_default();
    }

    entries
}

/// Parse `V{n}__{name>.sql` → (version, name).
fn parse_migration_filename(filename: &str) -> Option<(i32, String)> {
    let stem = filename.strip_suffix(".sql")?;
    let (version_str, name) = stem.split_once("__")?;
    let version = version_str.strip_prefix('V')?.parse::<i32>().ok()?;
    Some((version, name.to_string()))
}

/// Extract the table/view name and whether the statement creates a view from a
/// `CREATE TABLE [IF NOT EXISTS] name` or `CREATE VIEW [name]` statement.
fn extract_table_and_view(sql: &str) -> Option<(String, bool)> {
    let upper = sql.to_uppercase();
    let create_table = upper.find("CREATE TABLE");
    let create_view = upper.find("CREATE VIEW");

    let (keyword_len, is_view) = match (create_table, create_view) {
        (Some(pt), Some(pv)) if pv < pt => (11, true),
        (Some(_), _) => (12, false),
        (None, Some(_)) => (11, true),
        (None, None) => return None,
    };

    let keyword = if is_view {
        "CREATE VIEW"
    } else {
        "CREATE TABLE"
    };
    let pos = upper.find(keyword)?;
    let after = &sql[pos + keyword_len..];

    let rest = after.trim_start();

    let rest = if !is_view && rest.to_uppercase().starts_with("IF NOT EXISTS") {
        &rest["IF NOT EXISTS".len()..]
    } else {
        rest
    };

    let rest = rest.trim_start();
    let end = rest
        .find(|c: char| c.is_whitespace() || c == '(' || c == '\n' || c == '\r')
        .unwrap_or(rest.len());
    let name = rest[..end].trim();

    let name = name
        .strip_prefix('\'')
        .and_then(|s| s.strip_suffix('\''))
        .or_else(|| name.strip_prefix('"').and_then(|s| s.strip_suffix('"')))
        .or_else(|| name.strip_prefix('`').and_then(|s| s.strip_suffix('`')))
        .unwrap_or(name);

    Some((name.to_string(), is_view))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_filename_extracts_version_and_name() {
        assert_eq!(
            parse_migration_filename("V1__create_trades.sql"),
            Some((1, "create_trades".to_string()))
        );
        assert_eq!(
            parse_migration_filename("V4__create_view_lob.sql"),
            Some((4, "create_view_lob".to_string()))
        );
    }

    #[test]
    fn parse_filename_rejects_non_migration_files() {
        assert_eq!(parse_migration_filename("README.md"), None);
        assert_eq!(parse_migration_filename("V1__create_trades"), None);
        assert_eq!(parse_migration_filename("V__name.sql"), None);
    }

    #[test]
    fn collect_migrations_finds_all_files() {
        let entries = collect_migrations("src/db/migrations");
        assert_eq!(entries.len(), 4);
        assert_eq!(
            entries.iter().map(|e| e.version).collect::<Vec<_>>(),
            vec![1, 2, 3, 4]
        );
        assert_eq!(
            entries.iter().map(|e| e.name.as_str()).collect::<Vec<_>>(),
            vec![
                "create_trades",
                "create_lob_levels",
                "create_lob_snapshots",
                "create_view_lob"
            ]
        );
        assert_eq!(
            entries
                .iter()
                .map(|e| e.table_name.as_str())
                .collect::<Vec<_>>(),
            vec!["trades", "lob_levels", "lob_snapshots", "lob"]
        );
        assert_eq!(
            entries.iter().map(|e| e.is_view).collect::<Vec<_>>(),
            vec![false, false, false, true]
        );
    }

    #[test]
    fn extract_table_and_view_detects_views_and_tables() {
        assert_eq!(
            extract_table_and_view("CREATE TABLE IF NOT EXISTS trades (inst_id SYMBOL)"),
            Some(("trades".to_string(), false))
        );
        assert_eq!(
            extract_table_and_view("CREATE TABLE lob_levels (inst_id SYMBOL)"),
            Some(("lob_levels".to_string(), false))
        );
        assert_eq!(
            extract_table_and_view("CREATE VIEW 'lob' AS ( SELECT 1 )"),
            Some(("lob".to_string(), true))
        );
        assert_eq!(
            extract_table_and_view("CREATE VIEW my_view AS SELECT 1"),
            Some(("my_view".to_string(), true))
        );
    }
}
