CREATE TABLE IF NOT EXISTS trades (
    inst_id SYMBOL INDEX TYPE POSTING,
    exchange SYMBOL INDEX TYPE POSTING,
    trade_id SYMBOL,
    seq_id LONG,
    px DOUBLE,
    sz DOUBLE,
    side SYMBOL INDEX TYPE POSTING,
    latency LONG,
    ts TIMESTAMP
) TIMESTAMP(ts) PARTITION BY HOUR TTL 1 HOURS;
