CREATE TABLE IF NOT EXISTS lob_levels (
    inst_id SYMBOL INDEX TYPE POSTING,
    exchange SYMBOL INDEX TYPE POSTING,
    ts TIMESTAMP,
    side SYMBOL INDEX TYPE POSTING,
    price DOUBLE,
    size DOUBLE,
    best_diff DOUBLE,
    latency LONG
) TIMESTAMP(ts) PARTITION BY HOUR TTL 1 HOURS;
